version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "110:110"  # Nginx uchun 80-portni ochib qo'yish
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
