version: '3'

services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles  # Statik fayllar
      - media-data:/app/media  # Media fayllar
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "404:404"  # Nginx 404-portini ochamiz
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfiguratsiyasi
      - static-data:/app/staticfiles  # Statik fayllar
      - media-data:/app/media  # Media fayllar
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
