version: '3'

services:
  # Django ilovasi
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    command: gunicorn --bind 0.0.0.0:8052 config.wsgi:application  # Gunicorn orqali Django ilovasini ishga tushurish

  # Nginx (Web server)
  nginx:
    image: nginx:latest
    ports:
      - "95:95"  # Nginx tashqi 404 portni konteynerdagi 404 portga yo'naltiradi
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx konfiguratsiyasi
      - static-data:/app/staticfiles  # Statik fayllar
      - media-data:/app/media  # Media fayllar
    depends_on:
      - app  # Nginx ilovadan keyin ishga tushadi
    networks:
      - app-network

  # Redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6380"  # Redisni tashqi 6370 port orqali ulanish
    networks:
      - app-network

  # Celery
  celery:
    build: .
    command: celery -A config.celery.app worker --loglevel=info  # Celeryni ishga tushirish
    volumes:
      - .:/app
    depends_on:
      - redis  # Redis bo‘lishi kerak
      - app  # Django ilovasi bo‘lishi kerak
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Tarmoqlarni sozlash

volumes:
  static-data:  # Statik fayllar uchun volyum
  media-data:   # Media fayllar uchun volyum