services:
  app:
    build: .
    volumes:
      - .:/app
      - static-data:/app/staticfiles
      - media-data:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "404:404"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles
      - media-data:/app/media
    depends_on:
      - app
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6380:6380"
    networks:
      - app-network

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-data:
  media-data:
